spring.application.name=dynamic-queries

spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/openapi/v3/api-docs
springdoc.pathsToMatch=/**
springdoc.default-produces-media-type=application-json

spring.datasource.url=${JDBC_CONNECTION_STRING:jdbc:h2:mem}:${DATABASE_NAME:userdb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.h2.Driver}